---
title: "Introduction to keystats"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Intro}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Anna Sophie Peters, Nurah Jaradat, Jiner Zheng 
### 12 December 2019

This function allows Twitter users to search the website by keyword or hashtag,
returning multiple graphics and statistical summaries such as a bar plot of 
related unique words, a word cloud, a radar chart, and two bar plots of location 
statistics.

```{r setup}
library(tweetstats)
keystats <- function(key,n=10000,top_num=10, graph_col = "dodgerblue3"){
  if(!is.numeric(n))
    stop("n must be numeric number no more than 18000", call. = FALSE)
  if(n>18000)
    stop("n should not exceed 18000", call. = FALSE)
  if(!is.numeric(top_num))
    stop("top_num must be numeric")
  key <- deparse(substitute(key))
  n <- deparse(substitute(n))
  top_num <- deparse(substitute(top_num))
  graph_col <- deparse(substitute(graph_col))

  # read in the template and modify it
  report <- readLines("inst/keystatsTemplate.txt")
  report <- gsub("xxxnum", n, report, fixed = TRUE)
  report <- gsub("xxxkeyword", key, report, fixed = TRUE)
  report <- gsub("xxxtop_num", top_num, report, fixed = TRUE)
  report <- gsub("xxxfill", graph_col, report, fixed = TRUE)

  # write out template
  tf <- tempfile(fileext = ".Rmd")
  to <- tempfile(fileext = ".Html")
  writeLines(report, tf)

  # render R markdown and display
  library(rmarkdown)
  render(input = tf,
         output_format = "html_document",
         output_file = to)
  file.show(to)

  invisible(to)
}
```
